### ISSUE TITLE
Back arrow disappears

### ISSUE THREAD

**Issue by YeapGuy** [Henry-ZHR/firefox_no_home_button#1]
Hi! This module works well, except for one issue: in Custom Tabs (I think that's how it's called) - that's the special type of Firefox that's used when you open a link in an app such as Discord or your email client - this module causes the back arrow (which returns you back to the app where you opened the link) to disappear.

I have no experience with xposed modules, but I assume what you're doing is removing the 1st button in the navbar or something similar. That button isn't always the home button though.

Screenshots attached before & after applying module.
![IMG_20220731_154929](https://user-images.githubusercontent.com/43749899/182029831-6cd66447-311d-4c0f-8069-8d65f9fe1090.jpg)
![IMG_20220731_155049](https://user-images.githubusercontent.com/43749899/182029850-b1e150e9-541c-420b-8279-ac5ae289010c.jpg)

**Comment by Henry-ZHR** [comment]
Should be fixed now

[app-release.zip](https://github.com/Henry-ZHR/firefox_no_home_button/files/9249842/app-release.zip)

Please test if it works

**Comment by YeapGuy** [comment]
Now it's fixed! Thanks very much!
