### ISSUE TITLE
Feature request: ReVanced module?

### ISSUE THREAD

**Issue by trlkly** [Henry-ZHR/firefox_no_home_button#2]
I'm thankful you made this Xposed module. But I wondered if you'd look into making a ReVanced module, too. Since ReVanced modifies the APK, not the app itself, it doesn't need root. And, with all the changes it can do in other apps like YouTube, Twitch, Citra, etc, I thought it might be able to remove the home button.

**Comment by Henry-ZHR** [comment]
Is there any documentation for developing a ReVanced module?

**Comment by Henry-ZHR** [comment]
If you just want to use the module without root, I think [Xpatch](https://github.com/WindySha/Xpatch) or [LSPatch](https://github.com/LSPosed/LSPatch) should be OK

**Comment by trlkly** [comment]
I don't know a ton about how ReVanced is organized behind the scenes. But it's a very convenient patching utility that I already use for the other apps I mentioned. All I can recommend is checking out their github page: https://github.com/revanced

That said, being able to patch the APK is the main thing I want (as I don't update Firefox all that often). That home button is why I'm still on an older version of Firefox (Beta), but I'm starting to feel the age. So thank you so much for letting me know that's possible with your module. 

At some point I should finish rooting my phone (as I've already unlocked it) but I've still not gotten around to it.

**Comment by Henry-ZHR** [comment]
Seems that they patch byte code, which I am not familiar with...

As Xpatch and LSPatch also work by modifying the apk, I don't think it's really necessary to port the module to ReVanced

**Comment by trlkly** [comment]
I wish to confirm that LSPatch did indeed work, though it did necessitate uninstalling the old version of Firefox. 

Getting Shizuku up and running was a bit of a pain, but I'm not entirely sure that was necessary.

**Comment by Henry-ZHR** [comment]
> I wish to confirm that LSPatch did indeed work, though it did necessitate uninstalling the old version of Firefox.
> 
> Getting Shizuku up and running was a bit of a pain, but I'm not entirely sure that was necessary.

It's said that Shizuku is not required. Seems it's only used to install the patched apk. You can still install it manually without Shizuku.
