### ISSUE TITLE
Fennec FDroid & Mull support 

### ISSUE THREAD

**Issue by dioxias** [Henry-ZHR/firefox_no_home_button#3]
Is there any potential for making this compatible with Fennec FDroid, and Mull browser?

**Comment by Henry-ZHR** [comment]
Should work out-of-box

**Comment by dioxias** [comment]
Ah! Indeed it does! Thank you!

**Comment by SievaFliesAlone** [comment]
Hi, I think it did work but stopped for Fennec.

version 119.1.0
org.mozilla.fennec_fdroid
versionCode 1191020

**Comment by Henry-ZHR** [comment]
> Hi, I think it did work but stopped for Fennec.
> 
> version 119.1.0 org.mozilla.fennec_fdroid versionCode 1191020

It works on my machine. `120.0.0 (Build #1200020)`

**Comment by SievaFliesAlone** [comment]
F-Droid:
![fennec an no home button module installed](https://github.com/Henry-ZHR/firefox_no_home_button/assets/790717/53c8e9a4-a185-4171-8d82-3dac9342395d)
Fennec:
![fennec with home button](https://github.com/Henry-ZHR/firefox_no_home_button/assets/790717/5225c871-efe6-4ed9-a09b-62ddf2ed1bc5)

What can I Do to fix this?

**Comment by Henry-ZHR** [comment]
@anibyl 

1. Does any other xposed module work on your phone?

2. Is Fennec in module scope?

**Comment by Henry-ZHR** [comment]
> Hi, I think it did work but stopped for Fennec.
> 
> version 119.1.0 org.mozilla.fennec_fdroid versionCode 1191020

What did you mean by "it did work"? Did it work for you?

**Comment by dioxias** [comment]
Chipping in to say, Mull and Fennec FDROID work for me still.

**Comment by SievaFliesAlone** [comment]
> 1. Does any other xposed module work on your phone?

My apologies. I think it worked on my previous phone that was LineageOS and rooted with some modules installed. My current phone runs unrooted GrapheneOS, and I don't think xposed modules can run on it.
Sorry!
