### ISSUE TITLE
app not removing home button

### ISSUE THREAD

**Issue by DudeYes** [Henry-ZHR/firefox_no_home_button#4]
Version of firefox for android: 124.2.0
Phone: xiaomi redmi note 13

**Comment by Henry-ZHR** [comment]
Works on my machine (`124.2.0 (Build #2016012559), 7a0e399c7b+`)

Did you enable the module correctly?

**Comment by DudeYes** [comment]
I probably haven't. I installed it by using droid-ify and once it was installed I could only open the details window of the app and nothing more so I figured configuration is automatic. What should I do to enable the module?

**Comment by Henry-ZHR** [comment]
This is an Xposed module so you need Xposed framework. I suggest [LSPosed](https://github.com/LSPosed/LSPosed) if you have root  or [LSPatch](https://github.com/LSPosed/LSPatch) if you don't. (But note that they're unmaintained)

**Comment by DudeYes** [comment]
Thank you for the instructions. I'm not going to use this module though because there's a lot of hoops I have to jump through to remove the home button which didn't bother me much in the first place.
