### ISSUE TITLE
make it work with Fennec please

### ISSUE THREAD

**Issue by clemenceaus** [Henry-ZHR/firefox_no_home_button#5]
Hey,

Fennec is my Firefox of choice as it removes most tracking.
Could you make this work with Fennec?
I have tried it on my device and it did remove the home button from the normal firefox version, but not from fennec.

Thanks! I would appreciate it very much!

Fennec: https://f-droid.org/de/packages/org.mozilla.fennec_fdroid/

**Comment by Henry-ZHR** [comment]
Works on my machine, `124.2.0 (Build #1242020), 7a0e399c7b+`

**Comment by clemenceaus** [comment]
Hey, I have just reinstalled the app and added it to root under KSU but its still showing. I even rebooted my device just to make sure.
Does it maybe not work with KSU?
Thanks for your fast reply.

![Screenshot_20240506-175314_KernelSU](https://github.com/Henry-ZHR/firefox_no_home_button/assets/166404729/e0dcf218-cae1-4195-9e14-27fb54e8f8b5)
![Screenshot_20240506-175305_Fennec](https://github.com/Henry-ZHR/firefox_no_home_button/assets/166404729/cc526c87-959f-43d3-adf9-3f637c623d16)

**Comment by Henry-ZHR** [comment]
You need Xposed framework, for example [LSPosed](https://github.com/LSPosed/LSPosed).

The module itself doesn't need root.

**Comment by clemenceaus** [comment]
Oh my bad, sorry for wasting your time haha.
