### ISSUE TITLE
Feature Request - Clear Tabs Between Sessions

### ISSUE THREAD

**Issue by c3t1nn** [Henry-ZHR/firefox_no_home_button#6]
Hi, thanks a lot for this little cool module. Working great on FF Nightly so far!
I wanted to make a feature request, if it's possible and if you have time to do it.

So the thing is, after the mobile redesign of Firefox, the tabs keep coming back when you open up Firefox again. Some liked this, and some didn't. But Mozilla never brought back this old default behavior as an option. They kind of brought it back with optional timing, like deleting tabs after one day/a week, etc.

As a dinosaur, I would be so happy to have this kind of option, if it's possible for you to do. Something like "Clear Tabs Between Sessions" or "Open homepage only, no tabs from previous session". I hope I am clear enough to explain it, and I just kindly wanted to ask you. Thank you for your work and efforts.

**Comment by clemenceaus** [comment]
Hey this is possible already (in Fennec at least).
Under "Delete browsing data on quit" your can select "Open tabs" and other things aswell.
Cheers

![Screenshot_20240505-214509_Fennec](https://github.com/Henry-ZHR/firefox_no_home_button/assets/166404729/42eb1562-6789-4d5c-a8e8-12f920318b40)

**Comment by Henry-ZHR** [comment]
There is existing implementation as @clemenceaus said and I won't spend time on it since I don't need such things.
